EX-1512 - Style the sicherearbeit.at section link list
OEGBVerlag/sicherearbeit-aem-sites30 pull request #12
Opened 2021-09-20 12:06 UTC by Bejor

![Bildschirmfoto 2021-09-20 um 14 05 24](https://user-images.githubusercontent.com/12427959/133999288-5860d7f8-2305-418f-8a9d-035ce9826a0f.png)

2021-09-20 14:28 UTC, martinkastler requested changes
I personally would remove the margin-left of the list. That margin is very problematic on oegb.at as well as on younion.at. I would rather start without margin-left and add it later, if people call for it.

![image](https://user-images.githubusercontent.com/88790097/134019773-6fd43112-c588-43b4-b93d-4b3b2c8045f0.png)

2021-09-20 15:53 UTC, Bejor commented
> I personally would remove the margin-left of the list. That margin is very problematic on oegb.at as well as on younion.at. I would rather start without margin-left and add it later, if people call for it.
> 
> ![image](https://user-images.githubusercontent.com/88790097/134019773-6fd43112-c588-43b4-b93d-4b3b2c8045f0.png)

removed the margin-left

2021-09-21 07:26 UTC, martinkastler approved these changes
Good.

2021-09-21 08:19 UTC, martinkastler approved these changes

2021-09-21 08:47 UTC, merged